FROM koyeb/docker-compose

# Set working directory
WORKDIR /app

# Copy the application code and configuration
COPY . /app

COPY .env.example /app/.env

# Make sure scripts are executable
RUN chmod +x /app/scripts/*.py || true

# Set entrypoint to run docker-compose with build flag
ENTRYPOINT ["docker-compose", "up", "--build"]